// <auto-generated />
namespace TP1Module6EntityFrameworkDojoPart2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ignorePotentiel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignorePotentiel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230915274_ignorePotentiel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
